# Generated by Django 3.0.6 on 2020-05-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBasic',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_value', models.TextField()),
                ('a_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemBasic',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_category', models.CharField(max_length=200)),
                ('p_question', models.TextField()),
                ('p_type', models.IntegerField()),
                ('p_diff', models.IntegerField()),
            ],
            options={
                'db_table': 'problems',
                'managed': False,
            },
        ),
    ]
