# Generated by Django 3.0.6 on 2020-05-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='answer',
        ),
    ]
