# Generated by Django 3.0.6 on 2020-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200514_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBasic',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_value', models.TextField()),
                ('a_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='problembasic',
            table='problems',
        ),
    ]
