# Generated by Django 3.0.6 on 2020-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uncorrets',
            field=models.ManyToManyField(blank=True, related_name='uncorret', to='problems.Problem'),
        ),
    ]
