# Generated by Django 3.0.6 on 2020-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprob',
            name='correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
