# Generated by Django 3.0.6 on 2020-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200606_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprob',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
