# Generated by Django 3.0.6 on 2020-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interprobs', '0002_auto_20200528_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
