# Generated by Django 3.0.6 on 2020-05-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('xnotes', '0002_auto_20200526_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xnote',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
    ]
