# Generated by Django 3.0.6 on 2020-05-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xnotes', '0004_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
